scitokens/scitokens

- src/scitokens/scitokens.py
- tests/test_with_http.py
Adding test when:
- Key id is not the first or only in the certs file
- When the key id does not exist in the certs file
> Adding key id tests

- src/scitokens/scitokens.py
If the token was not properly serialized (missing base64-encoded headers,
for example), we now throw an InvalidFormatException instead of a
MissingKeyException.
> Raise invalid format if token is not properly serialized.

- src/scitokens/scitokens.py
- tests/test_scitokens.py
This provides a more dictionary-like `__getitem__` and `get`, with the latter providing a mechanism to only allow verified claims.
Includes unit tests.
> Implement `__getitem__` for the SciToken object.  Fixes #24

- src/scitokens/scitokens.py
- tests/test_create_scitoken.py
- tests/test_scitokens.py
Given a token, allow the `Enforcer` object to parse it and generate a set of ACLs.
This allows downstream libraries (such as the `xrootd-scitokens`) to cache the logic in the Enforcer directly and skip the call to the `scitokens` library.
> Implement ACL generation in the Enforcer object.

- src/scitokens/utils/keycache.py
Fixes an exception when `XDG_CACHE_HOME` is set.
> Fix incorrect variable name.

- src/scitokens/scitokens.py
- tests/test_scitokens.py
Without this, any token containing the `sub` claim would fail the Enforcer.
Includes simple unit test.
> Add support for `sub` claim to the Enforcer.

- src/scitokens/utils/keycache.py
- tests/test_keycache.py
Adding next update time.  A timer when the cache will attempt to update the key, but if it fails, it's non-fatal.
> Adding next_update time

- src/scitokens/scitokens.py
- tests/test_create_scitoken.py
The ver (version) attribute enforces versions of scitokens
that it understands.
The opt (optional) attribute adds optional arguments that
the scitoken can contain.
> Adding ver (version) and opt (optional)

- src/scitokens/utils/config.py
- tests/test_config.py
Fix for when there is no config defined.  Forgot to capture "NoSectionError"
> Fix no config

- src/scitokens/scitokens.py
- tests/test_create_scitoken.py
Adding `__contains__` so that we can perform actions like:
if 'scp' in token:
> Add contains

- build-scripts/build_rpm.sh
osg-build is not in the release repo in osg 3.5, one needs to fetch it from devops-itb
> get osg-build from devops-itb repo

- MANIFEST.in
- configs/python-scitokens.spec
- setup.cfg
This PR adds new files to include the `LICENSE` file in distributions
- new MANIFEST.in for `setup.py sdist` tarballs
- new setup.cfg for `setup.py bdist_wheel` wheels
And modifies the spec file to include it in binary rpms.
> Include license in distributions

- src/scitokens/scitokens.py
Update of PyJWT dependency broke some behavior.
- New method to read unverified payload
- PyJWT serialize returns a string now, rather than bytes.=
> Fix dependencies

- src/scitokens/scitokens.py
- tests/test_create_scitoken.py
Add a method to perform token discovery according to
https://github.com/WLCG-AuthZ-WG/bearer-token-discovery/blob/master/specification.md
```
token = SciTokens.discover()
```
will attempt to read in a serialized token from the locations specified and return `IOError` if no tokens are available.
> Add WLCG discover method

- .github/workflows/python-package.yml
- tests/test_admin_create_key.py
- tests/test_config.py
- tests/test_create_scitoken.py
This PR updates the CI to run the `python-package` workflow on Windows and macOS, mainly to validate that the test suite passes on those platforms, and then fixes issues with the test suite on windows (at least).
> Run continuous integration on macOS and windows

- src/scitokens/scitokens.py
This PR patches `SciToken.serialize` to check all claims (i.e. including 'verified' claims) for the issuer, to allow repeated calls to `.serialize()` for the same token.
Without this change the following occurs:
```python
>>> from cryptography.hazmat.primitives.asymmetric.rsa import generate_private_key
>>> from scitokens import SciToken
>>> key = generate_private_key(public_exponent=65537, key_size=4096)
>>> token = SciToken(key=key)
>>> token["iss"] = "test"
>>> token.serialize()
b'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ0ZXN0IiwiZXhwIjoxNjI1MzE0ODQ4LCJpYXQiOjE2MjUzMTQyNDgsIm5iZiI6MTYyNTMxNDI0OCwianRpIjoiYTVhZWJhYzctOWU3OS00Y2I4LTk2MjUtNGZhM2NlZmU4NzM4In0.hn4mCt6TIrLDs1Q4eYH26MQm9xE2FinkFqK8ZLmTTNUzNHvI9ZWScdLJC5hNLyzARmymxc05rw-GRjgLgVa_i6wS4A99y6MCZA77vNYWXoneKpOhxDkq-oBuVAEyx8 …
```
> Check verified claims for issuer in SciToken.serialize

- src/scitokens/utils/errors.py
- src/scitokens/utils/keycache.py
This PR adds a new `SciTokensException` class as the parent for all of the existing exceptions defined in `scitokens.utils.errors`, to make it easier to catch all scitokens errors downstream (but not anything else).
> Add base SciTokensException class

- tests/test_admin_create_key.py
- tests/test_with_http.py
This PR modifies the test functions to reference files using paths relative to the CWD, mainly to allow the test suite to be executed from any directory (including from inside the `tests/` path itself, which currently doesn't work).
> Reference test files using relative paths

- tests/test_create_scitoken.py
This PR fixes a corner-case issue in the test suite where if the user has `TMPDIR` set to a path on a different device to `/tmp` the `os.rename` operation will fail. `shutil.move` can handle that.
> Use shutil.move instead of os.rename

- src/scitokens/scitokens.py
This PR fixes #110 by adding an error message to the `OSError` raised when `SciToken.discover` fails to identify a token.
> Add error message for when SciToken.discover doesn't find a token

- src/scitokens/scitokens.py
This PR fixes #130 by unravelling a potential mismatch with the `jwt.encode` return type.
> SciToken.serialize: fix str/bytes mismatch

- tests/test_keycache.py
It turns out doesnotexists.com - used in the test suite as a ridiculous URL that would clearly never work - has started returning content. This PR updates the bogus URL in the simplest way, by using the `.edu` top-level domain, which is (IMO) less likely to randomly be acquired and start returning content.
> Update the bogus url used in the tests

- src/scitokens/scitokens.py
This PR fixes a bug exposed when running with the RHEL/EPEL7 version of PyJWT in decoding a token with `audience=None`.
EDIT: fixes #133.
> Fix bug decoding a token with no audience

- configs/python-scitokens.spec
Otherwise, Yum decides to stick with the older version and updates
have to be done with 'yum swap'
> Add obsoletes for smoother Yum updates on EL7

- tests/test_create_scitoken.py
This PR fixes #129 by updating the supported-by-cryptography-but-not-by-scitokens algorithm to supported-by-really-old-cryptography-but-still-not-by-scitokens.
> Update algorithm used to test UnsupportedKeyException

- configs/python-scitokens.spec
This PR adds a `%check` stage to the `python-scitokens.spec` file to execute the pytest suite during `rpmbuild`. This should expose problems like #129, #130, and #133 earlier in the process.
This should be rebased after #134 is merged (presuming it is merged at all).
> Run test suite using pytest during rpmbuild

- requirements.txt
This PR exposes #130 in GHA by updating the `PyJWT` version reference in `requirements.txt` to match `setup.py` as updated in #123.
> Update pyjwt version in requirements.txt

- pyproject.toml
This file is now required for building Python packages, in the most general case.
> Add pyproject.toml file for PEP 517 builds

- setup.py
Setuptools is a runtime dependency of scitokens because it needs pkg_resources on import.
Note, pkg_resources is deprecated and should be replaced with importlib.metadata (requires Python >= 3.8) or the backport importlib_metadata (requires Python >= 3.7).
To reproduce the issue, try installing scitokens and then importing in a clean environment (that does not have setuptools installed):
```
$ pip install scitokens
Collecting scitokens
Downloading scitokens-1.7.0-py3-none-any.whl (23 kB)
Collecting six
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cryptography
Downloading cryptography-38.0.1-cp36-abi3-macosx_10_10_x86_64.whl (2.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 12.1 MB/s eta 0:00:00
Collecting PyJWT>=1.6.1
Using cached PyJWT-2.5.0-py3-none-any.whl …
```
> Install requires setuptools

- src/scitokens/scitokens.py
- tests/test_create_scitoken.py
The deserialize function should raise the MissingIssuerException in case issuer is not provided. This commit fixed the issue. Also, added the unittest for this change.
> Fix missing issuer problem in deserialize function

- src/scitokens/utils/keycache.py
- tests/test_keycache.py
Cache file directory creation requires to be done under try-catch block. This commit has fixed the issue. Also, added the unittest for this change.
> Fix issue in creating the cache file location

- configs/python-scitokens.spec
- tests/conftest.py
- tests/test_demo.py
Use the pytest --no-network option to turn off tests that require outgoing network access.
> Adding pytest integration to turn of networking tests

- src/scitokens/tools/admin_add_key.py
- src/scitokens/tools/admin_list_key.py
- src/scitokens/tools/admin_list_keys.py
- src/scitokens/tools/admin_remove_key.py
- src/scitokens/tools/admin_update_keys.py
- src/scitokens/utils/keycache.py
Outputs the contents of the database
- List / Add / Remove records in Keycache
- Update all records in Keycache
- Add a force update option
> Create simple CLI tool to examine keycache in Python and refresh all entries in keycache

- docs/source/conf.py
This PR fixes broken sphinx docs builds by addressing outdated `intersphinx_mapping` syntax.
> Fix syntax for intersphinx_mapping in sphinx config

- README.rst
- src/scitokens/scitokens.py
- tests/test_scitokens.py
This PR patches the `Enforcer._validate_iss` method to support a sequence of valid `issuer` values.
This allows validating that a token was issued by one in a range of issuers, which is required for the LIGO-Virgo-KAGRA community, which uses separate production and test issuers, and as trialling HTCondor AP token issuers.
Closes #161
> Patch Enforcer to validate against multiple issuers

- src/scitokens/scitokens.py
This PR modifies the use of `logging` in the main `scitokens.py` module to use `DEBUG` messages, not `INFO`, since these seem to be for debugging purposes, rather than informing the user.
This also removes the logging message from the `_validate_jti` method, since that method doesn't actually do anything. The message has confused at least two different (sets of) users in LIGO who presumed that a network call was being made.
> Use debug logging, and remove confusing message

- .github/workflows/packaging.yml
- .github/workflows/python-package.yml
- configs/python-scitokens.spec
This PR updates the github actions packaging workflow to not use centos, and now use RHEL7. Builds are now for RL 8 and 9 (and Fedora).
> Update github actions packaging workflow
