scitokens/scitokens

src/scitokens/__init__.py, src/scitokens/scitokens.py, tests/scitokens_unittests.py
This implements the `Validator` object as described in the README.
=> Create a stub validation object and tests.

src/scitokens/scitokens.py
Really, this is just a test of the Codacy integration...
=> Fix trailing whitespace

src/scitokens/scitokens.py, src/scitokens/urltools.py, tests/create_sample_token.py, tests/test_urltools.py
urltools is a fine project, but it's a bit of a heavy hammer for only
normalizing paths.  This simply copies the path normalization and
unquoting logic into a scitokens helper module.
Includes various test cases.
=> Copy required functions from urltools into scitokens.

src/scitokens/scitokens.py, src/scitokens/utils/keycache.py, tests/create_sample_token.py, tests/test_create_scitoken.py, tests/test_scitokens.py
This fixes up some minor codacy issues - particularly with unit test coverage.
In particular, once merged, this will finish up the "Hello, World!" project board.
=> Fixup Codacy issues; improve unit test coverage

src/scitokens/scitokens.py, src/scitokens/utils/errors.py, src/scitokens/utils/keycache.py, tests/create_sample_token.py, tests/create_webserver.py, tests/test_scitokens.py, tests/test_with_http.py
Mostly documentation and whitespace fixes.
=> Various small nitpicks from Codacy.

configs/python-scitokens.spec
Super small change, going to merge.
=> Adding changelog message

src/scitokens/scitokens.py, tests/test_create_scitoken.py
=> Adding autodetection of the algorithm

tests/test_admin_create_key.py, tools/scitokens-admin-create-key
Fixes #78 
I tested this with just simple commands.
=> Adding EC to the admin-create-key

.travis.yml, tools/scitokens-admin-create-token
Adding python 3.7 to test matrix
=> Fixing token create for python 3

build-scripts/build_rpm.sh
install python3-devel and python3-setuptools and point to osg 3.5 repo inside the container used by travis to tests new commits
=> install python3-devel and python3-setuptools and point to osg 3.5 repo

src/scitokens/utils/keycache.py, tests/test_admin_create_key.py, tests/test_config.py, tests/test_keycache.py
This PR fixes compatibility with Windows. The changes to the library are trivial, most changes are in the test suite.
=> A few fixes to enable Windows compatibility

configs/python-scitokens.spec, setup.py
Fixes #120. @duncanmmacleod note that we're aiming for releases in OSG 3.5 and 3.6
=> Update packaging for 1.6.1 (SOFTWARE-4879)

configs/README.release.md, configs/python-scitokens.spec, src/scitokens/__init__.py
Missed a spot with the wrong version and added a release README
=> Ensure Python lib and RPM versions match (SOFTWARE-4879)

.github/workflows/packaging.yml, MANIFEST.in, configs/python-scitokens.spec
This PR adds a new github actions workflow to build RPMs with rpmbuild.
=> Add rpmbuild github actions workflow

tests/test_keycache.py
This PR improves the test suite by using `unittest.mock` to simulate the necessary error to test `UnableToCreateCache`, rather than trying to contrive a situation where that error happens for real.
=> Use unittest.mock to check UnableToCreateCache

README.rst
=> small typo fix in readme

README.rst, setup.py
This PR adds some links to readthedocs as requested by @djw8605.
=> Add links to readthedocs in some places

.github/workflows/python-coverage.yml, .github/workflows/python-package.yml, .github/workflows/python-publish.yml
This PR adds calls to `pip list installed` in a number of places in the CI, basically before doing anything useful, should help with debugging/sanity checking.
=> Run pip list installed to show packages

requirements.txt, setup.py, src/scitokens/scitokens.py, src/scitokens/utils/config.py, tests/test_config.py
=> do not use six

configs/python-scitokens.spec, setup.py, src/scitokens/__init__.py, src/scitokens/urltools.py, src/scitokens/utils/keycache.py
Will leave this open as I go through the Fedora packaging review.
https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2181686
=> Adding python scitokens spec file changes for review

src/scitokens/scitokens.py, tests/test_scitokens.py
=> Allow ['ANY'] to be treated as ANY
